<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\infrastructure\Triumph.HealthMS.ExternalServices\Triumph.HealthMS.ExternalServices.csproj" />
      <ProjectReference Include="..\Triumph.HealthMS.Commands\Triumph.HealthMS.Commands.csproj" />
      <ProjectReference Include="..\Triumph.HealthMS.Queries\Triumph.HealthMS.Queries.csproj" />
      <ProjectReference Include="..\Triumph.HealthMS.Service.Defaults\Triumph.HealthMS.Service.Defaults.csproj" />
    </ItemGroup>

</Project>
