<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Triumph.HealthMS.Domain\Triumph.HealthMS.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\HealthFacilities\" />
    </ItemGroup>

</Project>
