namespace Triumph.HealthMS.Shared.Enums;

public enum PermissionValue
{
    VIEW_PATIENTS_PROFILE = 1,
    MANAGE_PATIENTS_PROFILE = 2,
    UPDATE_TENANT_INFO = 3,
    DELETE_PATIENTS = 4,
    MANAGE_HEALTH_FACILITIES = 5,
    MANANGE_EMPLOYEES = 6,
    MANAGE_PATIENTS_MEASUREMENTS = 7,
    MANAGE_PATIENTS_CONSULTINGS = 8,
    MANAGE_PATIENTS_MEDICATIONS = 9,
    CREATE_CONSULTATION =  10,
    UPDATE_CONSULTATION_NOTES = 11,
}